/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:7b03398c-347e-41f2-90c1-2530942f9168",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_S2v6fNfYP",
    "aws_user_pools_web_client_id": "6v609nmgsids6olc0j793jetu1",
    "oauth": {}
};


export default awsmobile;
